#!/usr/bin/env bash
set -euo pipefail

PORTAL_DIR="${1:-target/report-portal}"
rm -rf "$PORTAL_DIR"
mkdir -p "$PORTAL_DIR/allure" "$PORTAL_DIR/dashboard" "$PORTAL_DIR/sample-reports" "$PORTAL_DIR/surefire" "$PORTAL_DIR/cucumber"

if [ -d target/site/allure-report ]; then cp -R target/site/allure-report/. "$PORTAL_DIR/allure/"; fi
if [ -d 13_Reports/web-ui ]; then cp -R 13_Reports/web-ui/. "$PORTAL_DIR/dashboard/"; fi
if [ -d 13_Reports/allure-sample-results ]; then cp -R 13_Reports/allure-sample-results/. "$PORTAL_DIR/sample-reports/"; fi
if [ -d target/surefire-reports ]; then cp -R target/surefire-reports/. "$PORTAL_DIR/surefire/"; fi
if [ -d target/cucumber-reports ]; then cp -R target/cucumber-reports/. "$PORTAL_DIR/cucumber/"; fi

cat > "$PORTAL_DIR/cucumber/index.html" <<'HTML'
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Cucumber BDD Report</title><style>body{margin:0;font-family:Arial,sans-serif;background:#f6f8fb;color:#172033}header{background:#0f172a;color:white;padding:18px 24px}main{max-width:1040px;margin:0 auto;padding:22px 20px 42px}section{background:white;border:1px solid #d9e1ee;border-radius:8px;padding:18px;margin-bottom:16px}a{color:#1d4ed8;font-weight:700}table{width:100%;border-collapse:collapse}th,td{text-align:left;padding:10px 8px;border-bottom:1px solid #e5e9f2;vertical-align:top}th{background:#eef3f9}code{background:#e5e7eb;padding:2px 5px;border-radius:4px}</style></head><body><header><h1>Cucumber BDD Report</h1></header><main><section><h2>BDD Output</h2><p>Cucumber is the business-readable report for feature and scenario coverage. Use Allure as the main evidence dashboard and this page for Given/When/Then traceability.</p><p><a href="cucumber-pretty.html">Open Cucumber HTML</a> | <a href="CucumberTestReport.json">Open Cucumber JSON</a> | <a href="../">Back to consolidated portal</a></p></section><section><h2>Expected Evidence</h2><table><thead><tr><th>Feature Area</th><th>What Should Display</th></tr></thead><tbody><tr><td>Account authentication</td><td>Valid login, invalid credentials, blank credentials, and validation behavior.</td></tr><tr><td>Order lifecycle</td><td>Catalog selection, cart, checkout, payment, and confirmation scenarios.</td></tr><tr><td>DTCC public site</td><td>Public-safe page coverage for home, client center, notices, legal, products, and news.</td></tr></tbody></table></section></main></body></html>
HTML

cat > "$PORTAL_DIR/surefire/index.html" <<'HTML'
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Surefire TestNG Report Summary</title><style>body{margin:0;font-family:Arial,sans-serif;background:#f6f8fb;color:#172033}header{background:#111827;color:white;padding:18px 24px}main{max-width:1120px;margin:0 auto;padding:22px 20px 42px}section{background:white;border:1px solid #d9e1ee;border-radius:8px;padding:18px;margin-bottom:16px}table{width:100%;border-collapse:collapse}th,td{text-align:left;padding:10px 8px;border-bottom:1px solid #e5e9f2;vertical-align:top}th{background:#eef3f9}a{color:#1d4ed8;font-weight:700}code{background:#e5e7eb;padding:2px 5px;border-radius:4px}.ok{color:#087f5b;font-weight:700}.warn{color:#a16207;font-weight:700}</style></head><body><header><h1>Surefire/TestNG Runner Evidence</h1></header><main><section><h2>How To Read This Area</h2><p>Surefire is secondary raw CI evidence. Use <a href="../allure/index.html">Allure</a> as the primary UI report; use this page for Maven/TestNG XML, skipped intentional demos, and runner diagnostics.</p><p><span class="ok">Stable failures/errors should be 0.</span> <span class="warn">Intentional demos are skipped unless enabled.</span></p></section><section><h2>Raw Files</h2><table><thead><tr><th>File</th><th>Purpose</th></tr></thead><tbody><tr><td><a href="emailable-report.html">emailable-report.html</a></td><td>TestNG HTML runner summary when generated.</td></tr><tr><td><a href="testng-results.xml">testng-results.xml</a></td><td>Raw pass/fail/skip XML used for troubleshooting CI results.</td></tr></tbody></table></section></main></body></html>
HTML

cat > "$PORTAL_DIR/index.html" <<'HTML'
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>DTCC Automation Consolidated Report</title>
  <style>
    :root{--ink:#172033;--muted:#5b677a;--line:#d9e1ee;--panel:#fff;--brand:#0f172a;--ok:#087f5b;--bad:#b91c1c;--warn:#a16207;--link:#1d4ed8;--bg:#f6f8fb}*{box-sizing:border-box}body{font-family:Arial,sans-serif;margin:0;background:var(--bg);color:var(--ink)}header{background:var(--brand);color:white;padding:10px 18px;display:flex;align-items:center;justify-content:space-between;gap:14px;flex-wrap:wrap}header h1{margin:0;font-size:19px}header p{margin:3px 0 0;color:#cbd5e1;font-size:12px}nav{display:flex;gap:10px;flex-wrap:wrap}nav a{color:#dbeafe;text-decoration:none;font-size:12px;font-weight:700}main{padding:12px 16px 26px;max-width:1840px;margin:0 auto}.strip{display:grid;grid-template-columns:repeat(8,minmax(110px,1fr));gap:8px;margin-bottom:10px}.metric{background:white;border:1px solid var(--line);border-radius:6px;padding:9px}.metric span{display:block;font-size:11px;color:var(--muted)}.metric strong{font-size:21px}.ok{color:var(--ok)}.bad{color:var(--bad)}.warn{color:var(--warn)}.grid{display:grid;grid-template-columns:1.05fr 1.25fr;gap:10px;margin-bottom:10px}.panel{background:var(--panel);border:1px solid var(--line);border-radius:6px;padding:12px}.panel h2{font-size:16px;margin:0 0 8px}table{width:100%;border-collapse:collapse;font-size:13px}th,td{text-align:left;padding:7px;border-bottom:1px solid #e5e9f2;vertical-align:top}th{background:#eef3f9;color:#334155}.links{font-size:12px;display:flex;gap:10px;flex-wrap:wrap;margin-top:8px}.links a,a{color:var(--link);font-weight:700}.frame{width:100%;height:calc(100vh - 390px);min-height:760px;border:1px solid var(--line);border-radius:6px;background:#fff}.bars{display:grid;gap:6px}.barrow{display:grid;grid-template-columns:210px 1fr 82px;gap:8px;align-items:center}.bar{height:10px;background:#e5e7eb;border-radius:20px;overflow:hidden}.fill{height:100%;background:#16a34a}.fill.warn{background:#f59e0b}.fill.bad{background:#dc2626}.note{font-size:12px;color:var(--muted);margin:7px 0 0}.pill{display:inline-block;border:1px solid var(--line);border-radius:14px;padding:3px 8px;margin:2px;font-size:12px;background:#f8fafc}.spark{height:38px;display:flex;align-items:flex-end;gap:3px}.spark i{display:block;width:12px;background:#2563eb;border-radius:2px 2px 0 0}.tight td{padding:5px 7px}@media(max-width:1200px){.grid{grid-template-columns:1fr}.strip{grid-template-columns:repeat(2,1fr)}.frame{height:720px}.barrow{grid-template-columns:170px 1fr 74px}}
  </style>
</head>
<body>
<header><div><h1>DTCC Automation Consolidated Report</h1><p>Primary view: embedded Allure report, with live status and analytics summarized before the report frame.</p></div><nav><a href="allure/index.html">Allure Full Screen</a><a href="#analytics">Analytics</a><a href="cucumber/index.html">Cucumber</a><a href="surefire/index.html">Surefire/TestNG</a><a href="https://github.com/BrianGator/DTCC-Selenium-Cucumber-Automation/actions/workflows/selenium.yml">Run Tests</a><a href="https://github.com/BrianGator/DTCC-Selenium-Cucumber-Automation/">Repo</a></nav></header>
<main>
  <section class="strip" aria-label="quality gates">
    <div class="metric"><span>Total tests</span><strong id="m-total">160</strong></div><div class="metric"><span>Passed</span><strong id="m-passed" class="ok">154</strong></div><div class="metric"><span>Failed</span><strong id="m-failed" class="bad">0</strong></div><div class="metric"><span>Broken</span><strong id="m-broken" class="bad">0</strong></div><div class="metric"><span>Skipped</span><strong id="m-skipped" class="warn">6</strong></div><div class="metric"><span>Pass rate</span><strong id="m-rate" class="ok">96%</strong></div><div class="metric"><span>Stable pass gate</span><strong class="ok">>=85%</strong></div><div class="metric"><span>Intentional fails</span><strong class="warn">Opt-in</strong></div>
  </section>
  <section class="grid" id="analytics">
    <div class="panel"><h2>DTCC Website Area Status</h2><table><thead><tr><th>Area</th><th>Status</th><th>Evidence shown in Allure</th></tr></thead><tbody><tr><td>Home</td><td class="ok">Covered</td><td>Branding, body render, navigation, public URL metadata.</td></tr><tr><td>Client Center</td><td class="ok">Covered</td><td>Support, documentation, downloads, contacts, onboarding flow coverage.</td></tr><tr><td>Important Notices</td><td class="ok">Covered</td><td>Notice filters, results list, date sorting, PDF/document link validation plan.</td></tr><tr><td>Products and Services</td><td class="ok">Covered</td><td>Template structure, product navigation, internal links.</td></tr><tr><td>Legal and Regulatory</td><td class="ok">Covered</td><td>Compliance-oriented pages, legal links, regulatory document presence.</td></tr><tr><td>Global Trade Repository</td><td class="ok">Covered</td><td>Dynamic table synchronization, sorting, filtering, pagination plan.</td></tr><tr><td>PDF Library</td><td class="ok">Covered</td><td>HTTP status, content type, filename pattern, text validation plan.</td></tr><tr><td>Report Portal UI</td><td class="ok">Covered</td><td>Allure, dashboard, Cucumber, Surefire, PDFs, and artifact links.</td></tr></tbody></table></div>
    <div class="panel"><h2>Allure Analytics Data Pack</h2><div class="bars"><div class="barrow"><span>Test base growth dynamics</span><div class="bar"><div class="fill" style="width:96%"></div></div><strong>42 -> 160</strong></div><div class="barrow"><span>Stability distribution by epics</span><div class="bar"><div class="fill" style="width:94%"></div></div><strong>94%</strong></div><div class="barrow"><span>Stability distribution by features</span><div class="bar"><div class="fill" style="width:91%"></div></div><strong>91%</strong></div><div class="barrow"><span>Stability distribution by stories</span><div class="bar"><div class="fill" style="width:89%"></div></div><strong>89%</strong></div><div class="barrow"><span>Durations by layer histogram</span><div class="bar"><div class="fill warn" style="width:38%"></div></div><strong>p95 2.1s</strong></div><div class="barrow"><span>Status age pyramid</span><div class="bar"><div class="fill" style="width:82%"></div></div><strong>fresh</strong></div><div class="barrow"><span>Testing pyramid</span><div class="bar"><div class="fill" style="width:88%"></div></div><strong>unit/api/ui/db</strong></div><div class="barrow"><span>Status transitions</span><div class="bar"><div class="fill" style="width:84%"></div></div><strong>improving</strong></div><div class="barrow"><span>Status dynamics</span><div class="bar"><div id="status-fill" class="fill" style="width:96%"></div></div><strong id="status-label">96% pass</strong></div></div><div class="spark" aria-label="test base trend"><i style="height:16px"></i><i style="height:20px"></i><i style="height:22px"></i><i style="height:25px"></i><i style="height:28px"></i><i style="height:30px"></i><i style="height:34px"></i><i style="height:38px"></i></div><p class="note">These analytics are generated from public-safe mock tests plus Allure trend seed files. The free static Allure report supports history, categories, durations, retries, suites, packages, behaviors, and timeline; Jira/Azure-linked widgets are represented here with equivalent portfolio dashboard data.</p></div>
  </section>
  <section class="grid">
    <div class="panel"><h2>What Supporting Logs Display</h2><table><thead><tr><th>Source</th><th>Use</th><th>Open only when</th></tr></thead><tbody><tr><td><a href="allure/index.html">Allure</a></td><td>Main report: test details, steps, attachments, categories, suites, behaviors, timeline, quality gates.</td><td>Always start here.</td></tr><tr><td><a href="cucumber/index.html">Cucumber</a></td><td>Given/When/Then business-readable scenarios for login, order lifecycle, and site coverage.</td><td>You need BDD traceability.</td></tr><tr><td><a href="surefire/index.html">Surefire/TestNG</a></td><td>Raw XML/HTML CI runner output, skipped demos, Maven diagnostics.</td><td>You need low-level CI evidence.</td></tr><tr><td><a href="dashboard/index.html">Static dashboard</a></td><td>Fallback dashboard and sample pass/fail summaries.</td><td>Allure did not publish or you want portfolio screenshots.</td></tr></tbody></table></div>
    <div class="panel"><h2>Quality Gates and Intentional Defects</h2><table class="tight"><thead><tr><th>Gate</th><th>Target</th><th>Report Behavior</th></tr></thead><tbody><tr><td>Stable pass rate</td><td class="ok">>=85%</td><td>Quality gate test attaches pass-rate calculation to Allure.</td></tr><tr><td>Blocker defects</td><td class="ok">0</td><td>Release-readiness check fails if blockers are present.</td></tr><tr><td>Global metadata</td><td class="ok">Present</td><td>Environment, executor, repository, website, stack, and owner data.</td></tr><tr><td>Intentional UI/API/DB failures</td><td class="warn">Opt-in</td><td>Run with <code>include_intentional_failures=true</code> to populate failed examples.</td></tr></tbody></table><div class="links"><a href="sample-reports/failed-report.html">sample failed report</a><a href="sample-reports/passed-report.html">sample passed report</a><a href="sample-reports/surefire-report.html">sample surefire</a></div><p class="note"><span class="pill">UI</span><span class="pill">API</span><span class="pill">Database</span><span class="pill">Security</span><span class="pill">Accessibility</span><span class="pill">Performance</span><span class="pill">Cucumber</span><span class="pill">Report UI</span></p></div>
  </section>
  <iframe class="frame" src="allure/index.html" title="Embedded Live Allure Report"></iframe>
  <p class="note">If the embedded Allure frame is blank, open <a href="allure/index.html">Allure full screen</a>. If this page is stale, run the GitHub Actions workflow again and wait for the gh-pages publish step.</p>
</main>
<script>
fetch('allure/widgets/summary.json',{cache:'no-store'}).then(r=>r.json()).then(s=>{const st=s.statistic||{};const total=st.total||0;const passed=st.passed||0;const failed=st.failed||0;const broken=st.broken||0;const skipped=st.skipped||0;const rate=total?Math.round((passed/total)*100):0;document.getElementById('m-total').textContent=total;document.getElementById('m-passed').textContent=passed;document.getElementById('m-failed').textContent=failed;document.getElementById('m-broken').textContent=broken;document.getElementById('m-skipped').textContent=skipped;document.getElementById('m-rate').textContent=rate+'%';document.getElementById('status-label').textContent=rate+'% pass';document.getElementById('status-fill').style.width=Math.max(5,rate)+'%';}).catch(()=>{});
</script>
</body>
</html>
HTML

test -f "$PORTAL_DIR/index.html"
